server:
  port: ${API_SERVER_PORT:8081}
  servlet:
    application-display-name: notifications-ms
spring:
  application:
    name: notifications-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka