spring:
  datasource:
    url: jdbc:postgresql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:5432}/service_ms
    username: ${DB_CONNECTION_USERNAME:postgres}
    password: ${DB_CONNECTION_PASSWORD:postgres}
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update