server:
  port: ${API_SERVER_PORT:8083}
  servlet:
    application-display-name: service-catalog-ms
spring:
  application:
    name: service-catalog-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka