server:
  port: ${API_SERVER_PORT:8082}
  servlet:
    application-display-name: customer-ms
spring:
  application:
    name: customer-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka