server:
  port: ${API_SERVER_PORT:8080}
  servlet:
    application-display-name: user-management-ms
spring:
  application:
    name: user-management-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka