spring:
  kafka:
    topics:
      sms-otp: "sms-otp-notification-topic"
      email-otp: "email-otp-notification-topic"
    producer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost}:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        max.block.ms: 20000
        delivery.timeout.ms: 30000
    admin:
      properties:
        bootstrap.servers: ${KAFKA_HOST_NAME:localhost}:9092
    consumer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost}:${KAFKA_PORT:9092}
      group-id: notification-group-id