server:
  port: ${API_SERVER_PORT:8084}
  servlet:
    application-display-name: reservation-ms
spring:
  application:
    name: reservation-ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka